local dap = require('dap')
vim.keymap.set('n', '<F5>', dap.continue, {desc = 'continue'})
vim.keymap.set('n', '<F10>', dap.step_over, {desc = 'step over'})
vim.keymap.set('n', '<F11>', dap.step_into, {desc = 'step into'})
vim.keymap.set('n', '<F12>', dap.step_out, {desc = 'step out'})
vim.keymap.set('n', '<Leader>b', dap.toggle_breakpoint, {desc = 'toggle breakpoint'})
vim.keymap.set('n', '<Leader>B', dap.set_breakpoint, {desc = 'set breakpoint'})
vim.keymap.set('n', '<Leader>lp', function() dap.set_breakpoint(nil, nil, vim.fn.input('Log point message: ')); end, {desc = 'set breakpoint with message'})
vim.keymap.set('n', '<Leader>dr', dap.repl.open, {desc = 'repl'})
vim.keymap.set('n', '<Leader>dl', dap.run_last, {desc = 'run last'})
vim.keymap.set({'n', 'v'}, '<Leader>dh', function()
    require('dap.ui.widgets').hover()
end, {desc = 'ui: hover'})
vim.keymap.set({'n', 'v'}, '<Leader>dp', function()
    require('dap.ui.widgets').preview()
end, {desc = 'ui: preview'})
vim.keymap.set('n', '<Leader>df', function()
    local widgets = require('dap.ui.widgets')
    widgets.centered_float(widgets.frames)
end, {desc = 'ui: frames'})
vim.keymap.set('n', '<Leader>ds', function()
    local widgets = require('dap.ui.widgets')
    widgets.centered_float(widgets.scopes)
end, {desc = 'ui: scopes'})
